var _out=[];with($data){_out.push($util.value(a-b));
    _out.push('\n');
    _out.push($util.value($util.string_format(124.62,'%.1f')));
    _out.push('\n');
    var 'foo'=$util.strlen(search);_out.push('\n');
    var 'foo'=a+$util.strlen(search);_out.push(' ');
    _out.push("include语法不被支持");_out.push(' ');
    _out.push($util.value($util.escape(html,'html')));
    _out.push('\n');
    _out.push($util.value($util.escape('http://www.sohu.com?a=1&b=2','url')));
    _out.push('\n');
    _out.push($util.value($util.escape(javascript,'javascript')));
    _out.push('\n');
    _out.push($util.value($util.escape(searchInfo.s.a,'javascript')));
    _out.push('\n');
    _out.push($util.value($util.spacify('a b','f')));
    _out.push('\n');
    _out.push($util.value(7));
    _out.push('\n');
    _out.push($util.value($util.date_format(a,'%Y-%m-%d')));
    _out.push('\n');
    _out.push($util.value($util.capitalize('asdfasdf',true)));
    _out.push('\n');
    _out.push($util.value($util.fsize_format(12312312,'MB',3)));
    _out.push('\n');
    _out.push($util.value($util.nl2br('asdfasdf\nwww')));
    _out.push('\n');
    _out.push($util.value($util.cat('lowcase','111')));
    _out.push('\n');
    _out.push($util.value($util.replace('count_words','cou','comeon')));
    _out.push('\n');
    _out.push($util.value($util.upper('lowcase')));
    _out.push('\n');
    _out.push($util.value($util.strip('low ca se','^')));
    _out.push('\n');
};